-- ============================================
-- DAY 4 - SQL PRACTICE
-- TOPIC: JOINS + SUBQUERIES + CONDITIONAL AGGREGATION
-- Dataset: dbo.data
-- ============================================


-- Q1. Find the total number of transactions made by each country.
-- Use GROUP BY and ORDER BY to display the country with the highest
-- number of transactions first.
   SELECT Country,
   COUNT(DISTINCT InvoiceNo) AS NoOfTransactions
   FROM dbo.data
   GROUP BY Country
   ORDER BY NoOfTransactions DESC


-- Q2. Find the total revenue generated by each country.
-- Display Country and TotalRevenue.
-- Sort the results from highest revenue to lowest.
	SELECT 
	SUM(Quantity*UnitPrice) AS TotalRevenue,
	Country
	FROM dbo.data
	GROUP BY Country
	ORDER BY TotalRevenue DESC

-- Q3. Find the total spending of each customer and display their country.
-- Display:
-- CustomerID, Country, TotalSpending
-- Sort by TotalSpending from highest to lowest.
	SELECT 
	SUM(Quantity*UnitPrice) AS TotalSpending,
	Country,
	CustomerID
	FROM dbo.data
	GROUP BY Country,CustomerID
	ORDER BY TotalSpending DESC
-- Q4. Find the number of unique customers in each country.
-- Display:
-- Country, UniqueCustomers
-- Sort by the number of customers from highest to lowest.
	SELECT 
	COUNT(DISTINCT(CustomerID)) AS UniqueCustomers,
	Country
	FROM dbo.data
	GROUP BY Country
	ORDER BY UniqueCustomers DESC

-- Q5. Find the average order value for each country.
-- Calculate the total revenue divided by the number of invoices.
-- Display:
-- Country, AverageOrderValue
	SELECT 
	SUM(Quantity * UnitPrice) / COUNT(DISTINCT InvoiceNo) AS AverageOrderValue,
	Country
	FROM dbo.data
	GROUP BY Country


-- Q6. Find customers whose total spending is greater than
-- the average spending of all customers.
-- Display:
-- CustomerID, Country, TotalSpending
-- Use a CTE or subquery.
	WITH spend AS(
	     SELECT 
	     SUM(Quantity * UnitPrice) AS TotalSpending,
		 CustomerID,
		 Country
		 FROM dbo.data
		 GROUP BY CustomerID,Country)
    SELECT
	TotalSpending,
	CustomerID,
	Country
	FROM spend
	WHERE TotalSpending > (
    SELECT AVG(TotalSpending)
    FROM spend
	);
	

