-- Q1. Find the total spending of each customer and rank customers from highest to lowest spending using RANK().
SELECT 
CustomerID,
SUM(Quantity*UnitPrice) AS TotalSpending,
RANK() OVER(ORDER BY SUM(Quantity*UnitPrice) DESC) AS Rank
FROM dbo.data
GROUP BY CustomerID

-- Q2. Find the total spending of each customer and assign a ROW_NUMBER() based on their total spending.
SELECT
CustomerID,
SUM(Quantity*UnitPrice) AS TotalSpending,
ROW_NUMBER() OVER(ORDER BY SUM(Quantity*UnitPrice) DESC ) AS TotalSpending
FROM dbo.data
GROUP BY CustomerID

-- Q3. Find the top 3 customers from each country based on their total spending using RANK() and PARTITION BY.
SELECT *
FROM (
    SELECT
        Country,
        CustomerID,
        SUM(Quantity * UnitPrice) AS TotalSpending,
        RANK() OVER (
            PARTITION BY Country
            ORDER BY SUM(Quantity * UnitPrice) DESC
        ) AS CustomerRank
    FROM dbo.data
    GROUP BY Country, CustomerID
) AS RankedCustomers
WHERE CustomerRank <= 3
ORDER BY Country, CustomerRank;


-- Q4. Find the highest-spending customer from each country using ROW_NUMBER().
SELECT * 
FROM( SELECT 
       Country,
       CustomerID,
       SUM(Quantity * UnitPrice) AS TotalSpending,
       ROW_NUMBER() OVER(PARTITION BY Country ORDER BY SUM(Quantity*UnitPrice) DESC) AS RowNo
       FROM dbo.data 
       GROUP BY Country, CustomerID
 ) AS RankedCustomers
 WHERE RowNo=1
 ORDER BY Country DESC;


-- Q5. Using a CTE, find customers whose total spending is greater than the average spending of all customers.
WITH spend AS (
    SELECT 
        CustomerID,
        SUM(Quantity * UnitPrice) AS TotalSpending
    FROM dbo.data
    GROUP BY CustomerID
)
SELECT 
    CustomerID,
    TotalSpending
FROM spend
WHERE TotalSpending > (SELECT AVG(TotalSpending) FROM spend);


-- Q6. Using a CTE, calculate the total revenue generated by each product (StockCode) and rank products within each country.
WITH revenue AS(
        SELECT StockCode,
        Country,
        SUM(Quantity * UnitPrice) AS TotalRevenue
        FROM dbo.data
        GROUP BY StockCode,Country)
SELECT 
Country,
StockCode,
TotalRevenue,
RANK() OVER(PARTITION BY Country ORDER BY TotalRevenue DESC) AS Rank
FROM revenue

-- Q7. Using a CTE and a window function, find the top 3 products based on total revenue within each country.
WITH revenue AS (
    SELECT 
        Country,
        StockCode,
        SUM(Quantity * UnitPrice) AS TotalRevenue
    FROM dbo.data
    GROUP BY Country, StockCode
),
ranked_products AS (
    SELECT 
        Country,
        StockCode,
        TotalRevenue,
        RANK() OVER (
            PARTITION BY Country 
            ORDER BY TotalRevenue DESC
        ) AS Rank
    FROM revenue
)
SELECT 
    Country,
    StockCode,
    TotalRevenue,
    Rank
FROM ranked_products
WHERE Rank <= 3;
-- Q8. Calculate each customer's total spending and the average spending of all customers using a window function.
    WITH spend AS(
            SELECT 
            CustomerID,
            SUM(Quantity*UnitPrice) AS TotalSpending
            FROM dbo.data
            GROUP BY CustomerID)
    SELECT 
    CustomerID,
    TotalSpending,
    AVG(TotalSpending) OVER() AS AverageCustomers
    FROM spend
-- Q9. For each customer's transaction, use LAG() to display the previous transaction's UnitPrice ordered by InvoiceDate.
   SELECT 
   InvoiceDate,
   UnitPrice,
   LAG(UnitPrice,1) OVER(ORDER BY InvoiceDate) AS PrevTransaction
   FROM dbo.data

-- Q10. CHALLENGE: Find the top 3 customers from each country based on total spending and
--display their country rank, total spending, and average spending in that country.
   WITH spend AS (
    SELECT
        Country,
        CustomerID,
        SUM(Quantity * UnitPrice) AS TotalSpending
    FROM dbo.data
    GROUP BY Country, CustomerID
),
ranked AS (
    SELECT
        Country,
        CustomerID,
        TotalSpending,

        RANK() OVER(
            PARTITION BY Country
            ORDER BY TotalSpending DESC
        ) AS CountryRank,

        AVG(TotalSpending) OVER(
            PARTITION BY Country
        ) AS AvgSpending

    FROM spend
)
SELECT
    Country,
    CustomerID,
    CountryRank,
    TotalSpending,
    AvgSpending
FROM ranked
WHERE CountryRank <= 3;